### ISSUE TITLE
サンプルアプリ main.py に空白が存在するようです

### ISSUE THREAD

**Issue by mendelssohnbach** [shingenpy/fastapi_workshop#6]
[まずは普通に関数を作る](https://github.com/shingenpy/fastapi_workshop/tree/main/documents/04_create_app#%E3%81%BE%E3%81%9A%E3%81%AF%E6%99%AE%E9%80%9A%E3%81%AB%E9%96%A2%E6%95%B0%E3%82%92%E4%BD%9C%E3%82%8B)

`main.py`

`random_password =`の行頭に余分な空白が存在するようです。  
「作った関数を FastAPI アプリに書き換える」も同様  
「デプロイの下準備」も同様

```py
def get_password(length: int = 10, number: int = 10): 
    for _ in range(number):
         random_password = [random.choice(string.ascii_letters + string.digits) for i in range(length)]
        yield ''.join(random_password)
```

以下のように修正後動作しました。

```py
def get_password(length: int = 10, number: int = 10): 
    for _ in range(number):
        random_password = [random.choice(string.ascii_letters + string.digits) for i in range(length)]
        yield ''.join(random_password)   
```

**Comment by shingenpy** [comment]
@mendelssohnbach 指摘ありがとうございます。修正いたしました。
